<div class="regions f32" id="bendera" style="width: 830px;position: absolute;background: #f7f7f7;padding:10px;border-bottom:1px #e2e2e3 solid;display: none;">
                    
<ul>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="United States" r="US"><span class="flag us"></span> United States</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Japan" r="JP"><span class="flag jp"></span> Japan</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Korea, Republic of" r="KR"><span class="flag kr"></span> Korea, Republic of</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r hover" title="India" r="IN"><span class="flag in"></span> India</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Indonesia" r="ID"><span class="flag id"></span> Indonesia</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Philippines" r="PH"><span class="flag ph"></span> Philippines</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Canada" r="CA"><span class="flag ca"></span> Canada</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Russian Federation" r="RU"><span class="flag ru"></span> Russian Federation</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Taiwan, Province of China" r="TW"><span class="flag tw"></span> Taiwan, Province of China</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Singapore" r="SG"><span class="flag sg"></span> Singapore</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Germany" r="DE"><span class="flag de"></span> Germany</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Italy" r="IT"><span class="flag it"></span> Italy</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Hong Kong" r="HK"><span class="flag hk"></span> Hong Kong</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="United Kingdom" r="GB"><span class="flag gb"></span> United Kingdom</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="France" r="FR"><span class="flag fr"></span> France</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Thailand" r="TH"><span class="flag th"></span> Thailand</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Malaysia" r="MY"><span class="flag my"></span> Malaysia</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Viet Nam" r="VN"><span class="flag vn"></span> Viet Nam</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Turkey" r="TR"><span class="flag tr"></span> Turkey</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Spain" r="ES"><span class="flag es"></span> Spain</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Australia" r="AU"><span class="flag au"></span> Australia</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Morocco" r="MA"><span class="flag ma"></span> Morocco</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Sweden" r="SE"><span class="flag se"></span> Sweden</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="New Zealand" r="NZ"><span class="flag nz"></span> New Zealand</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Finland" r="FI"><span class="flag fi"></span> Finland</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Saudi Arabia" r="SA"><span class="flag sa"></span> Saudi Arabia</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Brazil" r="BR"><span class="flag br"></span> Brazil</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Romania" r="RO"><span class="flag ro"></span> Romania</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Poland" r="PL"><span class="flag pl"></span> Poland</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Greece" r="GR"><span class="flag gr"></span> Greece</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Austria" r="AT"><span class="flag at"></span> Austria</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Mexico" r="MX"><span class="flag mx"></span> Mexico</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Ireland" r="IE"><span class="flag ie"></span> Ireland</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Switzerland" r="CH"><span class="flag ch"></span> Switzerland</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Uganda" r="UG"><span class="flag ug"></span> Uganda</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Qatar" r="QA"><span class="flag qa"></span> Qatar</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Peru" r="PE"><span class="flag pe"></span> Peru</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Norway" r="NO"><span class="flag no"></span> Norway</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Netherlands" r="NL"><span class="flag nl"></span> Netherlands</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Israel" r="IL"><span class="flag il"></span> Israel</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Denmark" r="DK"><span class="flag dk"></span> Denmark</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="China" r="CN"><span class="flag cn"></span> China</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Chile" r="CL"><span class="flag cl"></span> Chile</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Argentina" r="AR"><span class="flag ar"></span> Argentina</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Tunisia" r="TN"><span class="flag tn"></span> Tunisia</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Pakistan" r="PK"><span class="flag pk"></span> Pakistan</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Hungary" r="HU"><span class="flag hu"></span> Hungary</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Colombia" r="CO"><span class="flag co"></span> Colombia</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Cameroon" r="CM"><span class="flag cm"></span> Cameroon</a></li>
<li style="list-style-type:none;padding:0px;width:33.3%;float:left;"><a href="javascript:void(0)" onClick="filter_negara(this,'<?="/webmaster/post/search/".getPermalink()->splice(4)."/?hl="?>')" style="color:#666" class="r" title="Central African Republic" r="CF"><span class="flag cf"></span> Central African Republic</a></li>
</ul>
                </div>