var $$={trim:function(s){return s.replace(/(^\s*)|(\s*$)/g,"");},format:function(){var s=arguments[0];for(var i=0;i<arguments.length- 1;i++){var reg=new RegExp("\\{"+ i+"\\}","gm");s=s.replace(reg,arguments[i+ 1]);}
return s;},getQueryString:function(name){var reg=new RegExp("(^|&)"+ name+"=([^&]*)(&|$)","i");var r=location.search.substr(1).match(reg);if(r!=null)return unescape(decodeURI(r[2]));return null;},bytesToSize:function(bytes){var sizes=['B','KB','MB','GB','TB','PB','EB','ZB','YB'];if(bytes==0)return'0 B';var i=parseInt(Math.floor(Math.log(bytes)/ Math.log(1024)));
if(i==0)return bytes+' '+ sizes[i];return(bytes/Math.pow(1024,i)).toFixed(1)+' '+ sizes[i];},random:function(min,max,exact){if(arguments.length===0){return Math.random();}else if(arguments.length===1){max=min;min=0;}
var range=min+(Math.random()*(max- min));return exact===void(0)?Math.round(range):range.toFixed(exact);},setCookie:function(name,value,days,domain,secure){var c=name+"="+ value;if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));c+="; expires="+ date.toGMTString();}
c+='; path=/';if(domain){c+='; domain='+ domain;}
if(secure){c+='; secure'}
document.cookie=c;},getCookie:function(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}
return null;},popup:function(u,n,w,h){var left=screen.width/2- w/2;var top=screen.height/2- h/2;return window.open(u,n,'toolbar=no,status=no,menubar=no,width='+ w+',height='+ h+',top='+ top+',left='+ left)},setUrlParam:function(url,param,value){var reg=new RegExp("([?&]"+ param+"=).*?(&|$)");value=encodeURIComponent(value);if(reg.test(url)){url=url.replace(reg,"$1"+ value+"$2");}else{url=[url,param+"="+ value].join(~url.indexOf('?')?'&':'?');}
return url;},setUrlParams:function(url,params){for(var param in params){if(params.hasOwnProperty(param)){url=$$.setUrlParam(url,param,params[param]);}}
return url;},removeUrlParam:function(url,param){return url.replace(new RegExp('[?&]'+ param+'=[^&#]*(#.*)?$'),'$1').replace(new RegExp('([?&])'+ param+'=[^&]*&'),'$1');},clearForm:function(id,str){var not_expr=':button, :submit, :reset, :hidden, :checkbox, :radio';if(str){not_expr+=','+str;}
id.find(':input').not(not_expr).val('');id.find(':checkbox, :radio').prop('checked',false);},btnLoad:function(id){id.attr('data-reset',id.text());id.attr('disabled','disabled');id.text(id.attr('data-load'));},btnReset:function(id){if(id.attr('data-reset')){id.text(id.attr('data-reset'));}
id.removeAttr('disabled');},initPage:function(){$(".lazy").lazyload({threshold:200});$('.loadmore').each(function(){(function(_this){_this.click(function(){if(_this.text()==$$lang['LOADING']){return false;}
var purl=_this.attr("href");var pcallid=_this.attr("data-callbackid");var ppage=Number(_this.attr("data-page"));var maxpage=Number(_this.attr("data-maxpage"));_this.text($$lang['LOADING']);var url=$$.setUrlParams(purl,{ajax:1});$.ajax({url:url,type:'get',success:function(data){_this.text($$lang['SHOW_MORE']);if(ppage>=maxpage){_this.hide();}
if($$.trim(data)){try{ga('send','pageview',$$.setUrlParams(purl,{page:ppage}));}catch(e){}
ppage++;_this.attr("data-page",ppage);_this.attr('href',$$.setUrlParams(purl,{page:ppage}));$('#'+ pcallid).append(data);var $category_template=$('ul#pagedata>li');var length=$category_template.length;if((length%24)>0){_this.hide();}
var begin=(ppage- 2)*24;$category_template.slice(begin,length).find('img.lazy').lazyload({threshold:200});}else{_this.hide();}}});return false;});})($(this));});},initTopics:function(){$(".lazygb_topic").lazyload({effect:"fadeIn"});$('.loadmore').each(function(){(function(_this){_this.click(function(){if(_this.text()==$$lang['LOADING']){return false;}
var purl=_this.attr("href");var pcallid=_this.attr("data-callbackid");var ppage=Number(_this.attr("data-page"));var maxpage=Number(_this.attr("data-maxpage"));_this.text($$lang['LOADING']);var url=$$.setUrlParams(purl,{ajax:1});$.ajax({url:url,type:'get',success:function(data){_this.text($$lang['SHOW_MORE']);if(ppage>=maxpage){_this.hide();}
if($$.trim(data)){try{ga('send','pageview',$$.setUrlParams(purl,{page:ppage}));}catch(e){}
ppage++;_this.attr("data-page",ppage);_this.attr('href',$$.setUrlParams(purl,{page:ppage}));$('#'+ pcallid).append(data);var $topic_template=$('ul#pagedata>li');var length=$topic_template.length;if((length%12)>0){_this.hide();}
var begin=(ppage- 2)*12;$topic_template.slice(begin,length).find('.lazygb_topic').lazyload({effect:"fadeIn"});}else{_this.hide();}}});return false;});})($(this));});},initDisqus:function(){var disqus_thread=$('#disqus_thread');if(disqus_thread.length>0){(function(){var d=document,s=d.createElement('script');s.src='';s.setAttribute('data-timestamp',+new Date());(d.head||d.body).appendChild(s);})();}
var comment_container=$('#comment_container');if(comment_container.length>0&&typeof(comment_config)!=='undefined'&&typeof(comment_url)!=='undefined'){comment_config.page.url=location.href;if(!comment_config.page.title){comment_config.page.title=document.title;}
comment_container.append('<iframe id="comment_iframe" src="'+ comment_url+'&'+ $.param(comment_config)+'" style="border: 0; width: 100%;" scrolling="no" frameborder="0"></iframe>')
iFrameResize({checkOrigin:false,bodyMargin:'10px',interval:100,minHeight:80,messageCallback:function(messageData){if(messageData.message==='remove'){$('.cssload-spin-box').remove();}}},'#comment_iframe');}},initAddthis:function(){(function(){var d=document,s=d.createElement('script');s.src='';s.async=1;(d.head||d.body).appendChild(s);})();},initAutocompleteDom:function(){var keys=new Bloodhound({datumTokenizer:Bloodhound.tokenizers.obj.whitespace('key'),queryTokenizer:Bloodhound.tokenizers.whitespace,prefetch:'/',remote:{url:'/api/v1/search_suggestion?key=%QUERY',wildcard:'%QUERY'}});$('.formsearch').each(function(){(function(_this){_this.find('.autocomplete').typeahead({hint:true,highlight:true,minLength:1},{displayKey:'key',source:keys,templates:{suggestion:function(data){return'<a href="javascript:void(0)">'+ data.key+'</a>';}}}).on("typeahead:selected",function(event,data,dataset){_this.submit();});})($(this));});$('.autocomplete').focus();},initAutocomplete:function(){var autocomplete=$('.autocomplete');if(autocomplete.length>0){autocomplete.one("click",function(){autocomplete.off("click");var d=document,s=d.createElement('script');s.src='';(d.head||d.body).appendChild(s);});}},initMenu:function(){$(window).on('hashchange',function(event){var e=event.originalEvent;if(e.oldURL&&e.oldURL.substr(-5)==='#menu'){if($('.shadow').css('display')==='block'){closeMenu();}else{window.history.go(-1);}}});var startX,deltaX;$('.menu,.shadow').on('touchstart',function(event){var touches=event.originalEvent.touches;if(touches&&touches.length){startX=touches[0].pageX;}}).on('touchmove',function(event){var touches=event.originalEvent.touches;if(touches&&touches.length){deltaX=startX- touches[0].pageX;}}).on('touchend',function(){if($('.ar_fix').length>0){if(deltaX<-80){closeMenu();}}else{if(deltaX>80){closeMenu();}}
deltaX=0;});$('#change_language').click(function(){$('.menu-locals').toggle();$('.menu-lang').toggleClass('menu-lang-down menu-lang-up')})},initBackTop:function(){var $backtop=$('#backtop');$(window).scroll(function(){if($(this).scrollTop()>500){if($backtop.is(':hidden')){$backtop.show();}}else{if($backtop.is(':visible')){$backtop.hide();}}});$('#backtop').click(function(){$('html,body').animate({scrollTop:0},500);});},gaEvent:function(str){var arr=str.split('|');if(arr.length==3){try{ga('send','event',arr[0],arr[1],arr[2]);}catch(e){}}},refEvent:function(str){if(str){$$.setCookie('_dl_ref',str,null,'',true);}},hostnames:{'localhost':1,'167.114.64.102':1,'www.':1,'':1,'m.':1},gaReferrer:function(tag){},initCategory:function(url){$('#sortselect').change(function(){$(this).attr('class',$(this).val());location.href=url+ $(this).val();});},initScrollList:function(){$('.box-scroll').each(function(){var $obj=$(this);var scroll=new IScroll($obj.get(0),{eventPassthrough:true,scrollX:true,scrollY:false,preventDefault:false,disablePointer:true,disableTouch:false,disableMouse:false});scroll.on('scrollEnd',function(){$obj.trigger('scroll');});$(".lazy1").lazyload({container:$obj});});},initADAegon:function(){if($('#ad-aegon-bottom-banner').length>0){if(ad_aegon_status=='close'){}else{$('#ad-aegon-bottom-banner .close').click(function(){$$.setCookie('ad_aegon','close',7);$('#ad-aegon-bottom-banner').hide();return true;});$('#ad-aegon-bottom-banner .down').click(function(){$$.setCookie('ad_aegon','close',7);setTimeout(function(){$('#ad-aegon-bottom-banner').hide();},2000);return true;});}}},initTouchSlide:function(id,lazygb_banner){TouchSlide({slideCell:id,titCell:".hd ul",mainCell:".bd ul",effect:"leftLoop",autoPage:true,startFun:function(i,c){if(lazygb_banner){$(id+' '+ lazygb_banner).lazyload();}},autoPlay:true,interTime:3000});if(lazygb_banner){$(id+' '+ lazygb_banner).lazyload();}},initIndex:function(){$$.initTopicScroll();$$.initScrollList();},initTopicScroll:function(){var $obj=$('.index-topic-wrap');var scroll=new IScroll($obj[0],{eventPassthrough:true,scrollX:true,scrollY:false,preventDefault:false,disablePointer:true,disableTouch:false,disableMouse:false});scroll.on('scrollEnd',function(){$obj.trigger('scroll');});$('.lazy_topic').lazyload({container:$obj,effect:"fadeIn"});},initDetails:function(){var myScroll=new IScroll('#screen',{eventPassthrough:true,scrollX:true,scrollY:false,preventDefault:false,disablePointer:true,disableTouch:false,disableMouse:false});myScroll.on('scrollEnd',function(){$('#screen').trigger('scroll');});$('#screen').find('.lazy_screen').lazyload({container:$("#screen"),load:resetWidth});function resetWidth(a,b,c){var _this=$(this);_this.parent().css('width','auto');_this.css('width',c.width*255/c.height+'px')
setTimeout(function(){myScroll.refresh();},0);}
$('.tube-lazy').lazyload();$('#screen').find('a').click(function(e){e.preventDefault();var items=[];$('#screen a').each(function(){var item={};item.src=$(this).attr('href');item.w=$(this).attr('data-width');item.h=$(this).attr('data-height');items.push(item);});var pswpElement=$('.pswp')[0];var options={closeOnScroll:false,closeOnVerticalDrag:false,index:$(this).index(),arrowKeys:false,getThumbBoundsFn:function(index){var thumbnail=$('#screen a')[index];var pageYScroll=window.pageYOffset||document.documentElement.scrollTop;var rect=thumbnail.getBoundingClientRect();return{x:rect.left,y:rect.top+ pageYScroll,w:rect.width};}};var gallery=new PhotoSwipe(pswpElement,PhotoSwipeUI_Default,items,options);gallery.listen('imageLoadComplete',function(index,item){if(item.w<1||item.h<1){var $index=$('#screen').find('.b').children().eq(index);var img=new Image();img.src=item.src;img.onload=function(){item.w=this.width;item.h=this.height;$index.attr('data-width',this.width);$index.attr('data-height',this.height);gallery.invalidateCurrItems();gallery.updateSize(true);};}});gallery.init();})
var des_height=$('.description').height();if(des_height>180){$('#show-more').click(function(){$('#describe').css({'height':'auto','max-height':'none'});$(this).parent().remove();return false;});$('.show-more').show();}
$('#show-more-version').click(function(){$('.more-version').show();$(this).parent().remove();return false;});$('.versions dt').click(function(){var elem=$(this);elem.children('span').toggleClass('open');elem.next('dd').toggle();});$$.initScrollList();$('.pushbullet').click(function(){var $a=$(this);var tag=$a.attr('data-tag');var n=$a.attr('data-name');var p=$a.attr('data-package');if(tag){$$.popup('',0,0);}else{$$.popup('',0,0);}
ga('send','event','pushbullet','click',p);});$('#details-to-bottom').click(function(){var top=$('#comment').offset().top;$('html,body').animate({scrollTop:top-60},500);return false})},initVersions:function(){$(function(){$('.ver-item-m').click(function(e){var $ver_popup=$('.ver-popup');var _this=$(this);$ver_popup.html(_this.parents('a').next().html());$.magnificPopup.open({mainClass:'mfp-zoom-out',items:{src:'.ver-popup',type:'inline'},callbacks:{beforeOpen:function(){var vid=_this.attr('data-vid');var $vid=$('.v'+ vid);if(!_this.attr('data-c')&&($vid.length===2||$vid.length===3)&&$vid.html().trim()==''){var p=_this.attr('data-p');var lang=_this.attr('data-lang');$vid.html($$lang['LOADING']).show();$.ajax({url:'/api/www/command-version_more',data:{package:p,vid:vid,lang:lang},type:'post',success:function(data){if(data.error==0){_this.attr('data-c',1);$vid.html(data.doc)}}});}}},removalDelay:300,autoFocusLast:false});return false;})})},initDetailsDownload:function(){var download_link=$('#download_link');var gaAttr=download_link.attr('ga');$$.gaEvent(gaAttr);if(gaAttr){download_link.attr('ga',gaAttr.replace('download|','redownload|'));}
$$.initScrollList();},initSearch:function(total,keyword){$('.advanced').click(function(){$('.advanced i').toggleClass('hover');$('.regions').toggle();});$('.regions .r').click(function(){$('#hidregion').val($(this).attr('r'));$('.formsearch').submit();});$('.search-clear').click(function(){$('#hidregion').val('');$('.formsearch').submit();});var loadmore=$('.loadmore');$('#search-page').submit(function(){if(loadmore.text()==$$lang['LOADING']){return false;}
loadmore.text($$lang['LOADING']);$.ajax({url:$(this).attr('action'),data:$(this).serialize(),type:'get',success:function(data){$('#search-res').append(data);$(".lazy").lazyload();loadmore.text($$lang['SHOW_MORE']);var begin=parseInt($('#search-page-begin').val())+ 15;$('#search-page-begin').val(begin);if(begin>=total){loadmore.remove();}}});return false;});loadmore.click(function(){$('#search-page').submit();});if(keyword&&window.localStorage){var local_key=".search.history:v1";var local_value=window.localStorage.getItem(local_key);if(local_value){try{local_value=JSON.parse(local_value);if($.isArray(local_value)){var index=local_value.indexOf(keyword);if(index===-1){local_value.splice(0,0,keyword);}else{local_value.splice(index,1);local_value.splice(0,0,keyword);}
local_value.splice(20);window.localStorage.setItem(local_key,JSON.stringify(local_value))}else{throw new Error();}}catch(e){window.localStorage.removeItem(local_key);}}else{window.localStorage.setItem(local_key,JSON.stringify([keyword]))}}},initSearchHot:function(){if(window.localStorage){var local_key=".search.history:v1";var local_value=window.localStorage.getItem(local_key);if(local_value){try{local_value=JSON.parse(local_value);if($.isArray(local_value)&&local_value.length>0){var history_str='';var $history=$('.history-list');var path=$history.attr('data-path');for(var i=0;i<local_value.length;i++){history_str+='<li><a href="'+path+'?q='+encodeURIComponent(local_value[i])+'">'+local_value[i]+'</a></li>';}
$history.append(history_str);$('.history').show();}else{throw new Error();}}catch(e){window.localStorage.removeItem(local_key);}}
$('.history-delete').click(function(){$('.history').remove();window.localStorage.removeItem(local_key);})}},initDown:function(){function btnLoad(id){id.attr('data-reset',id.text());id.attr('disabled','disabled');id.text(id.attr('data-load'));}
function btnReset(id){if(id.attr('data-reset')){id.text(id.attr('data-reset'));}
id.removeAttr('disabled');}
$('#captcha_a').click(function(){$('#captcha_img').attr('src',$(this).attr('data-src')+'?'+ Math.random());return false;});$('#captcha_form').submit(function(){$('#captcha_form').find('.error').hide();btnLoad($('#captcha_form button[type=submit]'));$.ajax({url:$(this).attr('action'),data:$(this).serialize(),type:'GET',dataType:'jsonp',jsonp:'callback',success:function(data){switch(data.status_code){case'SUCCESS':location.href=data.down_url;var pkg=$('#region-package').val();ga('send','event','region',pkg,$('#region-hid').val());$$.gaEvent('download|'+ pkg+'|region_APK');break;case'CAPTCHA_ERROR':btnReset($('#captcha_form button[type=submit]'));$('#captcha_form').find('.error').show();break;}}});return false;});$('#select-region').click(function(){$('#select-region i').toggleClass('hover');$('.flags').toggle();});var isStartDown=false;$('#region-form').submit(function(){if(isStartDown){return false;}
$('#region-package').val($$.trim($('#region-package').val()));isStartDown=true;hideError();$('#region-submit').addClass('ing');$('#down-info').text($$lang['REGION_DOWN-DOWNLOADING']);$.ajax({url:$(this).attr('action'),data:$(this).serialize(),type:'post',success:function(data){if(data&&data.error==0){location.href=data.down_url;ga('send','event','region',data.package_name,$('#region-hid').val());$$.gaEvent('download|'+ data.package_name+'|region_APK');}else{switch(data.error){case 1:showError($$lang['REGION_DOWN-REGION_ERROR']);$('#region-submit').removeClass('ing');break;case 2:location.href=$$x_ll+'/search?q='+ $('#region-package').val()+'&region='+ $('#region-hid').val();break;case 3:showError($$lang['REGION_DOWN-INVALID_APP']+' <a target="_blank" href="'+ $$x_ll+'/search?q='+ $('#region-package').val()+'&region='+ $('#region-hid').val()+'">"'+ $$.format($$lang['REGION_DOWN-SEARCH_RESULTS'],$('#region-package').val())+'"</a>');$('#region-submit').removeClass('ing');break;case 4:location.href=$$x_ll+ data.url;break;case 5:$('#captcha_form').find('[name="package_name"]').val(data.package_name);$.magnificPopup.open({mainClass:'mfp-zoom-out',items:{src:'#captcha_form',type:'inline'},removalDelay:300,fixedContentPos:true,fixedBgPos:true});}
$('#down-info').text('');}
isStartDown=false;}});return false;});function hideError(){$('.banner-search-bg').removeClass('error');$('#region-package').removeClass('error');$('.region-down-err').hide();}
function showError(e){$('.banner-search-bg').addClass('error');$('#region-package').addClass('error');$('.region-down-err span').html(e);$('.region-down-err').show();}
$('.region-down-err .close').click(function(){hideError();return false;});},setFlag:function(obj){var $obj=$(obj);$('#region-hid').val($obj.attr('title'));$('#select-region').attr('title',$obj.attr('title')).html($obj.find('span').clone()).append($obj.attr('title')+'<i></i>');$('#flags').hide();return false;},initRedirect:function(){$('.lang-no').click(function(){Redirect.setLangCookie('en');$('.lang-tip').toggleClass('lang-tip-open');setTimeout(function(){$('.lang-tip').toggleClass('lang-hide')},500)});if(Redirect.isShowLangTip){$('.lang-reason span').html($$lang['LANG_TIP'][Redirect.langGoll])
$('.lang-no').text($$lang['LANG_IGNORE'][Redirect.langGoll])
$('.lang-yes').text($$lang['LANG_OK'][Redirect.langGoll]).attr('href',Redirect.langGoUrl)
$('.lang-tip').toggleClass('lang-hide').toggleClass('lang-tip-open')}},initLoginRegister:function(){$(document).on('click','.cmt-popup [data-social]',function(){popup($(this).attr('data-social'));});$(document).on('submit','#cmt-login-form',function(){var _this=$(this);var $submit=_this.find('[type=submit]');_this.find('.cmt-input-error').removeClass('cmt-input-error');btnDisabled($submit);var $cmt_popup_error=_this.find('.cmt-popup-error');var $input_account=_this.find("[name='account']");var $input_password=_this.find("[name='password']");var account=$input_account.val().trim();var password=$input_password.val();var data={account:account,password:password};if($$.checkAccount(account)){if($$.checkPassword(password)){login_register_submit(_this,data);}else{popupInputError($input_password);$cmt_popup_error.text($$lang['USER-INCORRECT_PASSWORD']).show();btnRemoveDisabled($submit);}}else{popupInputError($input_account);$cmt_popup_error.text($$lang['USER-INCORRECT_ACCOUNT']).show();btnRemoveDisabled($submit);}});$(document).on('submit','#cmt-register-form',function(){var _this=$(this);var $submit=_this.find('[type=submit]');_this.find('.cmt-input-error').removeClass('cmt-input-error');btnDisabled($submit);var $cmt_popup_error=_this.find('.cmt-popup-error');var $input_account=_this.find("[name='account']");var $input_email=_this.find("[name='email']");var $input_password=_this.find("[name='password']");var $input_password_r=_this.find("[name='password_r']");var account=$input_account.val().trim();var email=$input_email.val().trim();var password=$input_password.val();var password_r=$input_password_r.val();var data={account:account,email:email,password:password};if($$.checkAccount(account)){if($$.checkPassword(password)){if(password==password_r){login_register_submit(_this,data);}else{popupInputError($input_password);popupInputError($input_password_r);$cmt_popup_error.text($$lang['USER-PASSWORD_NOT_MATCH']).show();btnRemoveDisabled($submit);}}else{popupInputError($input_password);$cmt_popup_error.text($$lang['USER-PASSWORD_MUST']).show();btnRemoveDisabled($submit);}}else{popupInputError($input_account);$cmt_popup_error.text($$lang['USER-USERNAME_MUST']).show();btnRemoveDisabled($submit);}});$(document).on('click','.cmt-captcha_a',function(){var _this=$(this);_this.find('img').attr('src',$(this).attr('data-src')+'?'+ Math.random());return false;});function login_register_submit(_this,data){var $cmt_popup_loading=_this.parent().find('.cmt-popup-loading');$cmt_popup_loading.show();if(_this.find("[name='captcha']").length>0){data.captcha=_this.find("[name='captcha']").val().trim();}
_this.find('.cmt-popup-error').hide();$.ajax({type:'POST',url:_this.attr('action'),data:data,success:function(data){$cmt_popup_loading.hide();btnRemoveDisabled(_this.find('[type=submit]'));if(data.error){_this.find('.cmt-popup-error').text(data.msg).show();if(data.status_code=='ACCOUNT_NOT_EXIST'||data.status_code=='INCORRECT_ACCOUNT'||data.status_code=='ACCOUNT_EXIST'){popupInputError(_this.find("[name='account']"))}
if(data.status_code=='INCORRECT_PASSWORD'){popupInputError(_this.find("[name='password']"));popupInputError(_this.find("[name='password_r']"))}
if(data.status_code=='INCORRECT_EMAIL'){popupInputError(_this.find("[name='email']"))}
if(data.status_code=='INCORRECT_CAPTCHA'){popupInputError(_this.find("[name='captcha']"))}}else{success();}}});}
function popupInputError($input){$input.addClass('cmt-input-error');}
function btnDisabled($btn){$btn.attr('disabled','disabled');}
function btnRemoveDisabled($btn){$btn.removeAttr('disabled');}
function popup(social){var opts={"width":700,"height":520,"menubar":"no","resizable":"yes","location":"yes","scrollbars":"no","centered":true};window.open('/auth/'+ social,"Connect",popupOptionsToString(popupOptionsResolveCentered(opts)));}
function popupOptionsToString(options){return Object.keys(options).map(function processOption(key){return key+'='+ options[key];}).join(',');}
function popupOptionsResolveCentered(options){var result=options;var width=window.outerWidth- options.width;var height=window.outerHeight- options.height;if(options.centered){result.left=options.left||Math.round(window.screenX+(width/2));result.top=options.top||Math.round(window.screenY+(height/2.5));delete result.centered;}
return result;}
function success(){var next=$$.getCookie('__next');if(next){location.href=decodeURIComponent(next)}else{location.href=$$x_ll_root;}}
window.popupResult=function(data){if(data){if(!data.error){if(data.user&&data.user.local_user=='web'){success();}}else{$('.cmt-popup').find('.cmt-popup-error').text('Error').show();}}};},checkAccount:function(account){var account_reg=/[ \f\n\r\t\v`~!@#\$%\^\&\*\(\)=\+<>\?:"\{\},\\\/;'\[\]\|]+/;if(account.length>=1&&account.length<=20&&!account_reg.test(account)){return true;}
return false;},checkPassword:function(password){if(password.length>=6&&password.length<=32){return true;}
return false;},hideAlert:function($alert){setTimeout(function(){$alert.hide();},2000)},initProfile:function(){$(function(){$("#select_month, #select_year").change(function(){var e,i;var $select_day=$("#select_day");var s=parseInt($("#select_year").val());var r=parseInt($("#select_month").val());if(s>0&&r>0){$("option",$select_day).not("[value='0']").remove();switch(r){case 2:e=s%4===0&&s%100!==0||s%400===0?29:28;break;case 4:case 6:case 9:case 11:e=30;break;default:e=31}
for(i=1;i<=e;i++){$select_day.append($("<option/>").text(i).val(i))}}});$('#form_contact').submit(function(){var _this=$(this);var data={};var day=_this.find('[name=birth_day]').val().trim();var month=_this.find('[name=birth_month]').val().trim();var year=_this.find('[name=birth_year]').val().trim();var nickName=_this.find('[name=nickName]').val().trim();var email=_this.find('[name=email]').val().trim();if(day&&month&&year){if(month<10){month='0'+ month;}
if(day<10){day='0'+ day;}
data.birthday=year+'-'+ month+'-'+ day;}
data.nickName=nickName;data.email=email;if(_this.find('[name=gender]:checked').length>0){data.gender=_this.find('[name=gender]:checked').val().trim();}
_this.find('.alert').hide();$$.btnLoad(_this.find('button[type=submit]'));$.ajax({url:_this.attr('action'),data:data,type:'POST',success:function(data){if(data.error){_this.find('.alert').removeClass('success').addClass('error').text(data.msg).show();}else{$('#nav-user-name').text(data.user.display_name);_this.find('.alert').removeClass('error').addClass('success').text($$lang['USER-SAVED_SUCCESS']).show()
$$.hideAlert(_this.find('.alert'))}
$$.btnReset(_this.find('button[type=submit]'));}});return false;});$('.picture a').click(function(){$.magnificPopup.open({mainClass:'mfp-zoom-out',items:{src:'.pre_pop_ca',type:'inline'},autoFocusLast:false,removalDelay:300});})})},initPassword:function(){$(function(){function checkPassword($password,password){if($$.checkPassword(password)){$password.removeClass('error').addClass('success');return true;}else{$password.removeClass('success').addClass('error');alertError($$lang['USER-PASSWORD_MUST']);return false;}}
function alertError(msg){$('#form_contact .alert').removeClass('success').addClass('error').text(msg).show();}
$('#form_contact').submit(function(){var _this=$(this);var data={};var $input_password=_this.find("[name='password']");var $input_password_n=_this.find("[name='password_n']");var $input_password_r=_this.find("[name='password_r']");var password=$input_password.val();var password_n=$input_password_n.val();var password_r=$input_password_r.val();_this.find('.alert').hide();if(!(checkPassword($input_password,password)&&checkPassword($input_password_n,password_n)&&checkPassword($input_password_r,password_r))){return false;}
if(password_n===password_r){$$.btnLoad(_this.find('button[type=submit]'));data.password=password;data.newPassword=password_n;$.ajax({url:_this.attr('action'),data:data,type:'POST',success:function(data){if(data.error){if(data.statusCode==='INCORRECT_PASSWORD'){$input_password.removeClass('success').addClass('error')}
_this.find('.alert').removeClass('success').addClass('error').text(data.msg).show();}else{_this.find('.alert').removeClass('error').addClass('success').text($$lang['USER-SAVED_SUCCESS']).show()
$$.hideAlert(_this.find('.alert'))}
$$.btnReset(_this.find('button[type=submit]'));}});}else{$input_password_n.removeClass('success').addClass('error');$input_password_r.removeClass('success').addClass('error');alertError($$lang['USER-PASSWORD_NOT_MATCH']);}
return false;});})},initInvit:function(){$('.author-reply').click(function(){var top=$('#cmt-form').offset().top;$('html,body').animate({scrollTop:top-60},500);return false})}};(function(defaults,$,window,undefined){var type=['input:not([type]),input[type="color"],input[type="date"],input[type="datetime"],input[type="datetime-local"],input[type="email"],input[type="file"],input[type="hidden"],input[type="month"],input[type="number"],input[type="password"],input[type="range"],input[type="search"],input[type="tel"],input[type="text"],input[type="time"],input[type="url"],input[type="week"],textarea',"select",'input[type="checkbox"],input[type="radio"]'],allTypes=type.join(","),extend={},validateField=function(event,options){var status={pattern:true,conditional:true,required:true},field=$(this),fieldValue=field.val()||"",fieldValidate=field.data("validate"),validation=fieldValidate!==undefined?extend[fieldValidate]:{},fieldPrepare=field.data("prepare")||validation.prepare,fieldPattern=field.data("pattern")||($.type(validation.pattern)=="regexp"?validation.pattern:/(?:)/),fieldIgnoreCase=field.attr("data-ignore-case")||field.data("ignoreCase")||validation.ignoreCase,fieldMask=field.data("mask")||validation.mask,fieldConditional=field.data("conditional")||validation.conditional,fieldRequired=field.data("required"),fieldDescribedby=field.data("describedby")||validation.describedby,fieldDescription=field.data("description")||validation.description,fieldTrim=field.data("trim"),reTrue=/^(true|)$/i,reFalse=/^false$/i,fieldDescription=$.isPlainObject(fieldDescription)?fieldDescription:options.description[fieldDescription]||{},name="validate";fieldRequired=fieldRequired!=""?fieldRequired||!!validation.required:true;fieldTrim=fieldTrim!=""?fieldTrim||!!validation.trim:true;if(reTrue.test(fieldTrim)){fieldValue=$.trim(fieldValue);}
if($.isFunction(fieldPrepare)){fieldValue=String(fieldPrepare.call(field,fieldValue));}else{if($.isFunction(options.prepare[fieldPrepare])){fieldValue=String(options.prepare[fieldPrepare].call(field,fieldValue));}}
if($.type(fieldPattern)!="regexp"){fieldIgnoreCase=!reFalse.test(fieldIgnoreCase);fieldPattern=fieldIgnoreCase?RegExp(fieldPattern,"i"):RegExp(fieldPattern);}
if(fieldConditional!=undefined){if($.isFunction(fieldConditional)){status.conditional=!!fieldConditional.call(field,fieldValue,options);}else{var conditionals=fieldConditional.split(/[\s\t]+/);for(var counter=0,len=conditionals.length;counter<len;counter++){if(options.conditional.hasOwnProperty(conditionals[counter])&&!options.conditional[conditionals[counter]].call(field,fieldValue,options)){status.conditional=false;}}}}
fieldRequired=reTrue.test(fieldRequired);if(fieldRequired){if(field.is(type[0]+","+ type[1])){if(!fieldValue.length>0){status.required=false;}}else if(field.is(type[2])){if(field.is("[name]")){if($('[name="'+ field.prop("name")+'"]:checked').length==0){status.required=false;}}else{status.required=field.is(":checked");}}}
if(field.is(type[0])){if(fieldPattern.test(fieldValue)){if(event.type!="keyup"&&fieldMask!==undefined){var matches=fieldValue.match(fieldPattern);for(var i=0,len=matches.length;i<len;i++){fieldMask=fieldMask.replace(RegExp("\\$\\{"+ i+"(?::`([^`]*)`)?\\}","g"),matches[i]!==undefined?matches[i]:"$1");}
fieldMask=fieldMask.replace(/\$\{\d+(?::`([^`]*)`)?\}/g,"$1");if(fieldPattern.test(fieldMask)){field.val(fieldMask);}}}else{if(fieldRequired){status.pattern=false;}else{if(fieldValue.length>0){status.pattern=false;}}}}
var describedby=$('[id="'+ fieldDescribedby+'"]'),log=fieldDescription.valid;if(describedby.length>0&&event.type!="keyup"){if(!status.required){log=fieldDescription.required;}else if(!status.pattern){log=fieldDescription.pattern;}else if(!status.conditional){log=fieldDescription.conditional;}
describedby.html(log||"");}
if(typeof validation.each=="function"){validation.each.call(field,event,status,options);}
options.eachField.call(field,event,status,options);if(status.required&&status.pattern&&status.conditional){if(!!options.waiAria){field.prop("aria-invalid",false);}
if(typeof validation.valid=="function"){validation.valid.call(field,event,status,options);}
options.eachValidField.call(field,event,status,options);}else{if(!!options.waiAria){field.prop("aria-invalid",true);}
if(typeof validation.invalid=="function"){validation.invalid.call(field,event,status,options);}
options.eachInvalidField.call(field,event,status,options);}
return status;};$.extend({validateExtend:function(options){return $.extend(extend,options);},validateSetup:function(options){return $.extend(defaults,options);}}).fn.extend({validate:function(options){options=$.extend({},defaults,options);return $(this).validateDestroy().each(function(){var form=$(this);if(form.is("form")){form.data(name,{options:options});var fields=form.find(allTypes),namespace=options.namespace;if(form.is("[id]")){fields=fields.add('[form="'+ form.prop("id")+'"]').filter(allTypes);}
fields=fields.filter(options.filter);if(!!options.onKeyup){fields.filter(type[0]).on("keyup."+ namespace,function(event){validateField.call(this,event,options);});}
if(!!options.onBlur){fields.on("blur."+ namespace,function(event){validateField.call(this,event,options);});}
if(!!options.onChange){fields.on("change."+ namespace,function(event){validateField.call(this,event,options);});}
if(!!options.onSubmit){form.on("submit."+ namespace,function(event){var formValid=true;fields.each(function(){var status=validateField.call(this,event,options);if(!status.pattern||!status.conditional||!status.required){formValid=false;}});if(formValid){if(!options.sendForm){event.preventDefault();}
if($.isFunction(options.valid)){options.valid.call(form,event,options);}}else{event.preventDefault();event.stopImmediatePropagation();if($.isFunction(options.invalid)){options.invalid.call(form,event,options);}}});}}});},validateDestroy:function(){var form=$(this),dataValidate=form.data(name);if(form.is("form")&&$.isPlainObject(dataValidate)&&typeof dataValidate.options.nameSpace=="string"){var fields=form.removeData(name).find(allTypes).add(form);if(form.is("[id]")){fields=fields.add($('[form="'+ form.prop("id")+'"]').filter(allTypes));}
fields.off("."+ dataValidate.options.nameSpace);}
return form;}});})({sendForm:true,waiAria:true,onSubmit:true,onKeyup:false,onBlur:false,onChange:false,nameSpace:"validate",conditional:{},prepare:{},description:{},eachField:$.noop,eachInvalidField:$.noop,eachValidField:$.noop,invalid:$.noop,valid:$.noop,filter:"*"},jQuery,window);(function($){$.fn.clearInput=function(options){var settings=$.extend({'focus':true},options);return this.each(function(){var $this=$(this);var $clear=$(settings.clear);$clear.click(function(){$this.val('').change();$clear.hide();if(settings.focus){$this.focus();}});function trigger(){if($this.val().length>0){$clear.show();}else{$clear.hide();}}
$this.on('keyup keydown change focus',function(){trigger();});trigger();});};})(jQuery);$(function(){$(".lazy").lazyload();var isUC=navigator.userAgent.indexOf('UCBrowser')>-1;$('.formsearch').submit(function(){if(!isUC){$(this).find('.search-button').addClass('search-load');}});$('.ga').click(function(){$$.gaEvent($(this).attr('ga'));return true;});$('.dl-ref').click(function(){$$.refEvent($(this).attr('dl-ref'));return true;});$('.amobile').click(function(){$$.setCookie('mobile','0',null,'');return true;});$$.initAutocomplete();$$.initMenu();$$.initAddthis();$$.initRedirect();console.log("\n %c  1.1.1 %c https:// \n\n","color: #FFFFFF; background: #030307; padding:5px 0;","color: #FFFFFF; background: #24cd77; padding:5px 0;")});